<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?= $this->view->getDescription();?>">
    <meta name="author" content="xavier ARNAL et édouard ViALE">

    <title><?=$this->view->getTitle();?></title>

    <!-- Bootstrap core CSS -->
    <link href="/assets/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="/css/main.css" rel="stylesheet">
</head>

<body>

      <?=$this->content;?>

    <footer class="col-lg-12 text-center">
<!--         <div class="container">
            <div class="row"> -->

                    <p>Copyright &copy; Xavier et Edouard</p>

<!--             </div>
        </div> -->
    </footer>

</body>

</html>
