<?php 
$this->setTitle('Mon compte');
$this->setDescription('Informations de l\'utilisateur');
?>

  <form class="form-horizontal" method = "post" action = "moncompte?action=modification">

      <h5> Identifiants </h5>

      <?php echo $this->form->input('email','Email'); ?>
      <?php echo $this->form->input('email_confirmation','Confirmer Email'); ?>
      <?php echo $this->form->input('mdp','Mot de passe',array('type'=>'password')); ?>
      <?php echo $this->form->input('mdp_confirmation','Confirmer mot de passe',array('type'=>'password')); ?>      

      <h5>Coordonnées </h5>

      <?php echo $this->form->input('societe','Société'); ?>
      <?php echo $this->form->input('nom','Nom'); ?>
      <?php echo $this->form->input('prenom','Prénom'); ?>  
      <?php echo $this->form->input('telephone','Téléphone'); ?> 
      
      <div class="col-xs-1 col-xs-offset-2">
        <input class="btn btn-danger btn-md" type="reset" name="reset" value="Recommencer" />
      </div>
      <div class="col-xs-offset-1 col-xs-6">
        <input class="btn btn-success btn-md" type="submit" name="submit" value="Modifier" />
      </div>

  </form>

  <a href="home" class="btn btn-success btn-lg"> Retour à l'acceuil </a> 

</div>